crossover_p = 0.8
mutation_p = 0.0001
phi_v = 0.05
phi_u = 0.0001
phi_r = 0.0005
phi_s = 0.01
max_gen = 5000
L_min_constant = 500
L_max_constant = 600
w1 = 0.0
w2 = 0.05
w3 = 0.1
w4 = 1000
sigma1 = -0.03
sigma2 = 0.001
sigma3 = 0.01
sigma4 = 0.01


GA_PARAMS = [
    # Original configuration
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "sigma1": sigma1,
        "sigma2": sigma2,
        "sigma3": sigma3,
        "sigma4": sigma4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
        {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
        {
        "max_gen": max_gen,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": phi_u,
        "phi_ru": 0.05,
        "phi_s": phi_s,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    """
    {
        "max_gen": 5000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": 5000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
        {
        "max_gen": 5000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": 5000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant,
        "use_objective": False,
    },
    {
        "max_gen": 20000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 20000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 20000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 20000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 20000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 20000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
        {
        "max_gen": 20000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 20000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 20000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 20000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "phi": 0.1,
        "phi_v": phi_v,
        "phi_r": phi_r,
        "phi_u": 0.8,
        "phi_ru": 0.05,
        "phi_s": 0.2,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 3000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 10,
        "w3": 0.4,
        "w4": 1000,
        "phi": 0.1,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 3000,
        "crossover_p": crossover_p,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 10,
        "w3": 0.4,
        "w4": 1000,
        "phi": 0.1,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 20000,
        "crossover_p": 0.3,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 10,
        "w3": 0.4,
        "w4": 1000,
        "phi": 0.5,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
  
    # Varying crossover_p
    {
        "max_gen": 2000,
        "crossover_p": 0.5,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.7,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    
    # Varying mutation_p
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": 0.05,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": 0.1,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    
    # Varying pop_size
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": mutation_p,
        "pop_size": 90,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": mutation_p,
        "pop_size": 110,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    
    # Varying w2
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 1,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 2,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 20,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    
    # Varying gene_segments
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 15,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 25,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    
    # Varying L_min_constant and L_max_constant
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 20,
        "L_min_constant": 80,
        "L_max_constant": 120
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 20,
        "L_min_constant": 100,
        "L_max_constant": 140
    },
    
    # Combined variations for more diverse experiments
    {
        "max_gen": 2000,
        "crossover_p": 0.5,
        "mutation_p": 0.05,
        "pop_size": 90,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 1,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 15,
        "L_min_constant": 80,
        "L_max_constant": 120
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.7,
        "mutation_p": 0.1,
        "pop_size": 110,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 2,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 25,
        "L_min_constant": 100,
        "L_max_constant": 140
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.5,
        "mutation_p": 0.1,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 1,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 20,
        "L_min_constant": 80,
        "L_max_constant": 120
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.7,
        "mutation_p": 0.05,
        "pop_size": 90,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 2,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 15,
        "L_min_constant": 100,
        "L_max_constant": 140
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": 0.05,
        "pop_size": 110,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 1,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 25,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.5,
        "mutation_p": mutation_p,
        "pop_size": 90,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 2,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 25,
        "L_min_constant": 80,
        "L_max_constant": 120
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.7,
        "mutation_p": mutation_p,
        "pop_size": 110,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 15,
        "L_min_constant": 100,
        "L_max_constant": 140
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": 0.1,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 2,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 20,
        "L_min_constant": 100,
        "L_max_constant": 140
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.5,
        "mutation_p": 0.05,
        "pop_size": 110,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 25,
        "L_min_constant": 80,
        "L_max_constant": 120
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.7,
        "mutation_p": 0.1,
        "pop_size": 90,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 1,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 15,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": 0.05,
        "pop_size": 90,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 2,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 20,
        "L_min_constant": 80,
        "L_max_constant": 120
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.5,
        "mutation_p": 0.1,
        "pop_size": 110,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 1,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 15,
        "L_min_constant": 100,
        "L_max_constant": 140
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.7,
        "mutation_p": mutation_p,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 2,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 25,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": 0.1,
        "pop_size": 110,
        "elite_indivs": 5,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "w4": w4,
        "gene_segments": 25,
        "L_min_constant": 100,
        "L_max_constant": 140
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.5,
        "mutation_p": 0.05,
        "pop_size": 100,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 2,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 15,
        "L_min_constant": L_min_constant,
        "L_max_constant": L_max_constant
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.7,
        "mutation_p": 0.05,
        "pop_size": 110,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 1,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 20,
        "L_min_constant": 80,
        "L_max_constant": 120
    },
    {
        "max_gen": 2000,
        "crossover_p": 0.3,
        "mutation_p": mutation_p,
        "pop_size": 90,
        "elite_indivs": 5,
        "w1": 0.6,
        "w2": 1,
        "w3": 0.4,
        "w4": 1000,
        "gene_segments": 15,
        "L_min_constant": 100,
        "L_max_constant": 140
    }
    """
]